# Generated by Django 5.1.5 on 2025-02-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название предмет', max_length=100, unique=True, verbose_name='Название предмет')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название предмет', max_length=100, verbose_name='Название предмет')),
                ('summary', models.TextField(help_text='Введите краткое описание учебного материала', max_length=1000, verbose_name='Учебный материал')),
                ('material_files', models.FileField(help_text='Загрузите файл с учебным материалом', upload_to='', verbose_name='Файл с учебным материалом')),
                ('subject', models.ForeignKey(help_text='Выберите учебны предмет', null=True, on_delete=django.db.models.deletion.CASCADE, to='jornal.subject', verbose_name='Учебны предмет')),
            ],
        ),
    ]
