# Generated by Django 5.1.5 on 2025-02-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalmaterial',
            name='material_files',
            field=models.FileField(help_text='Загрузите файл с учебным материалом', upload_to='material_files', verbose_name='Файл с учебным материалом'),
        ),
    ]
